---

  - name: copy id_rsa
    sudo: true
    copy: >
      src={{pg_config_id_rsa_path}}
      dest=/root/.ssh/id_rsa
      owner=root
      group=root
      mode=0600

  - name: copy id_rsa.pub
    sudo: true
    copy: >
      content="{{pg_config_public_key}}"
      dest=/root/.ssh/id_rsa.pub
      owner=root
      group=root
      mode=0600

  - name: add pgs to each other's known hosts
    sudo: true
    template: >
      src=known_hosts.j2
      dest=/root/.ssh/known_hosts
      owner=root
      group=root
      mode=0600

  - name: allow pgs to interconnect as root
    sudo: true
    authorized_key: >
      user=root
      key="{{pg_config_public_key}}"
